GET http://localhost:80/telefonos/telefonos.php/operadores
###
GET http://localhost:80/telefonos/telefonos.php/telefonos?codOperador=1
###
POST http://localhost:80/telefonos/telefonos.php/telefonos
Content-Type: application/x-www-form-urlencoded

telefono=123&codOperador=1&titular=Borja
###
GET http://localhost:80/telefonos/telefonos.php/telefonos?titular=pepe
###
PUT http://localhost:80/telefonos/telefonos.php/traspasos
Content-Type: application/x-www-form-urlencoded

motivo=prueba&telefono=600000000&nuevaOperadora=1
###
GET http://localhost:80/telefonos/telefonos.php/traspasos