package org.lebastudios.entities;

import lombok.Getter;
import lombok.Setter;

/**
 * EmpregadoProxecto generated by hbm2java
 */
@Setter
@Getter
public class EmpregadoProxecto implements java.io.Serializable
{
    private EmpregadoProxectoId id;

    private Empregado empregado;

    private Proxecto proxecto;
    private Integer horas;
}